# Generated by Django 4.0.1 on 2022-01-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_image',
        ),
    ]
