# Generated by Django 4.0.1 on 2022-01-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_delete_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images_three',
            field=models.ImageField(blank=True, upload_to='imagesss/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='images_two',
            field=models.ImageField(blank=True, upload_to='imagess/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, upload_to='images/products'),
        ),
    ]
