# Generated by Django 4.0.1 on 2022-01-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_images_three_product_images_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images_three',
            field=models.ImageField(blank=True, upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images_two',
            field=models.ImageField(blank=True, upload_to='images/products'),
        ),
    ]
