# Generated by Django 4.0.1 on 2022-02-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_variations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variations',
            options={'verbose_name': 'Variations', 'verbose_name_plural': 'Variations'},
        ),
        migrations.AddField(
            model_name='variations',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
