# Generated by Django 4.0.1 on 2022-02-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_variations_variation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Variation', 'verbose_name_plural': 'Variations'},
        ),
    ]
