# Generated by Django 4.0.1 on 2022-02-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_variation_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
