# Generated by Django 4.0.1 on 2022-02-09 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
