# Generated by Django 4.0.1 on 2022-02-09 14:22

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=44, null=True, size=4),
        ),
    ]
