# Generated by Django 4.0.1 on 2022-02-09 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_remove_subcategory_category'),
        ('store', '0017_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory'),
        ),
    ]
