# Generated by Django 4.0.1 on 2022-02-10 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_variation_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='brand',
        ),
    ]
