# Generated by Django 4.0.1 on 2022-02-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.IntegerField(default=0),
        ),
    ]
