# Generated by Django 4.0.1 on 2022-02-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_product_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
