# Generated by Django 4.0.1 on 2022-02-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='banner_img',
            new_name='banner_img1',
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_img2',
            field=models.ImageField(blank=True, upload_to='images/banner'),
        ),
    ]
