# Generated by Django 4.0.1 on 2022-02-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_rename_banner_img_banner_banner_img1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
