# Generated by Django 4.0.1 on 2022-02-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
