# Generated by Django 4.0.1 on 2022-02-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_subcategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'category'},
        ),
    ]
