# Generated by Django 4.0.1 on 2022-02-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_remove_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_offer',
            field=models.FloatField(default=0),
        ),
    ]
