# Generated by Django 4.0.1 on 2022-02-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_category_category_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_offer',
            field=models.IntegerField(default=0),
        ),
    ]
