# Generated by Django 4.0.1 on 2022-02-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_ip_alter_order_address_line_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_note',
        ),
    ]
