# Generated by Django 4.0.1 on 2022-02-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='delivery_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
