# Generated by Django 4.0.1 on 2022-02-22 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_offer',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
